README.md
=> Removed development part from README

report-ng/app/src/components/test-classes-card/test-classes-card.ts, report-ng/app/src/services/statistic-models.ts
Improved UI for horizontal test classes bar chart.
- Sort by amount of relevant statuses
- Increased column size for class names
=> Report ng/test class overview

driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverUtils.java
* Moves Selenium node detection to `testerra-selenoid-connector` module.
* Requires https://github.com/telekom/testerra-selenoid-connector/pull/6
=> Moved initialization of NodeInfo to SelenoidHelper

README.md, build.gradle
Made Jacoco support optional to prevent bugs during test execution.
=> Made Jacoco optional

report-ng/app/src/app.scss, report-ng/app/src/components/log-view/log-view.html, report-ng/app/src/components/log-view/log-view.ts, report-ng/app/src/components/logs/logs.ts, report-ng/app/src/services/statistics-generator.ts
* Show thread name in log message
* Link to method context details
*  Fixes #28 
=> Linked method log context to method details

core/src/main/java/eu/tsystems/mms/tic/testframework/report/model/context/AbstractContext.java
=> Filter new context by raw name instead of generate getName()

docs/src/docs/modules/localization.adoc
Update documentation for localization based on Unicode.
=> Improved documentation about making your build environment Unicode.

image-processing/build.gradle
Removed a dependency from the previous version of Testerra
=> Removed unneeded dependency

driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/GuiElementData.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/JSUtils.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/watchdog/WebDriverWatchDog.java
* Replaced `WeakHashMap` by `ConcurrentHashMap`.
* Prevent error messages on duplicate `WebDriverWatchdog` startup
Fixes #51
=> Minor optimizations

report-ng/app/src/components/classes/classes.ts
=> Handle param.status as string not number. Fixes #58

docs/src/docs/best-practices/html-elements.adoc
Documentation bugfix for shadow root elements.
=> Fixes documentation bug in shadow roots section

report-ng/app/src/components/test-classes-card/test-classes-card.ts
The previous PR didn't fix anything but made it worse. This is the right solution.
Fixes #57
=> Fixes #57 again by pushing null to the series data instead of 0

README.md, build.gradle, bup/README.md, bup/build.gradle, bup/src/main/java/eu/tsystems/mms/tic/testerra/bup/BrowserUpRemoteProxyManager.java, core/build.gradle, integration-tests/src/test/resources/log4j2-test.xml, report-model/build.gradle
- Fixes: #66
- Added Gradle report plugin for deep dependecy reports
=> Update version of some outdated dependencies (#66)

README.md, build.gradle, bup/README.md, bup/build.gradle, bup/src/main/java/eu/tsystems/mms/tic/testerra/bup/BrowserUpRemoteProxyManager.java, core-interop/build.gradle, core/build.gradle, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/page/AssertTextPageTest.java, integration-tests/src/test/resources/log4j2-test.xml, report-model/build.gradle
The update to TestNG 7.4.0 brings many bugfixes to TestNG (https://groups.google.com/g/testng-users/c/dwSJ04qeu8k). Especially the reducing of transitive dependencies (https://github.com/cbeust/testng/issues/2357) solves conflicts. For example JUnit was removed from dependency tree, no more confusion with JUnit asserts!
This PR includes #66.
=> Update TestNG to 7.4.0

core/src/main/java/eu/tsystems/mms/tic/testframework/utils/CertUtils.java, docs/src/docs/utilities/file-downloader.adoc, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/DefaultConnectionConfigurator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/FileDownloader.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java
=> Fixed parsing filename from Content Disposition header.

integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/page/CheckPageTest.java
=> Fixed testT08_CheckPage_ScreenshotOnLoad

core-interop/build.gradle, core-interop/src/main/java/eu/tsystems/mms/tic/testframework/utils/StringUtils.java, core/build.gradle, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/UITestUtils.java, image-processing/build.gradle, report-model/build.gradle, report-ng/build.gradle
I removed some transitive dependencies from some Testerra modules to prevent conflicts with your own project dependencies.
=> Removed some transitive dependencies

docs/src/docs/guielement/guielement-assertions.adoc, docs/src/docs/guielement/guielement-checks.adoc, docs/src/docs/guielement/guielement-waiters.adoc, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/DesktopGuiElementCore.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/GuiElement.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/ConfigurableGuiElementAssert.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/GuiElementAssert.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/GuiElementAssertDecorator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/PerformanceTestGuiElementAssert.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/GuiElementCoreDecorator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/GuiElementCoreSequenceDecorator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/GuiElementStatusCheck.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/GuiElementStatusCheckDecorator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/facade/GuiElementFacadeDecorator.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/facade/StandardGuiElementFacade.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/waiters/GuiElementWait.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/waiters/StandardGuiElementWait.java
Documentation updates
Fixes #86
=> Updated documentation for isVisible(). Fixes #86

report-ng/app/src/components/code-view/code-view.scss, report-ng/app/src/components/method-details/method.html, report-ng/app/src/components/method-details/method.ts
Show loading indicator when method details are loading.
=> Added loading indicator for method details.

core-interop/src/main/java/eu/tsystems/mms/tic/testframework/constants/TesterraProperties.java, docs/src/docs/execution/execution-watchdog.adoc, docs/src/docs/properties/execution-probs.adoc, docs/src/docs/properties/property-attributes.adoc, docs/src/docs/properties/webdriver-props.adoc, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/HttpClientFactory.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/hooks/DriverUiHook.java
Code refactored based on product owning meeting.
=> Disable WebDriverWatchdog by default and removed orphaned property

report-ng/app/src/components/dashboard/dashboard.html, report-ng/app/src/components/dashboard/dashboard.ts, report-ng/app/src/components/test-results-card/test-results-card.ts
Sets the filter properties from dashboard to URL for navigation purposes.
Fixes #105
=> The dashboard filter is now part of the URL. Fixes #105

bup/build.gradle, bup/src/main/java/eu/tsystems/mms/tic/testerra/bup/BrowserUpRemoteProxyManager.java, bup/src/main/java/eu/tsystems/mms/tic/testerra/bup/BrowserUpRemoteProxyServer.java, bup/src/test/java/eu/tsystems/mms/tic/testerra/bup/test/BupRemoteProxyManagerTest.java, docs/src/docs/modules/browser-up-proxy.adoc
Improved and updated Testerra BUP REST client to support the latest BrowsreUp proxy client. Fix also a setting to run BrowserUp proxy in a container.
Fixes #121 
=> Improved REST client for BrowserUp proxy

driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/UITestUtils.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverSessionsManager.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/UITestUtilsTest.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/webdrivermanager/WebDriverManagerTest.java
`UitTestUtils` now also takes screenshots from exclusive sessions.
Fixes #129 
=> Also take screenshots from exclusive sessions. Fixes #129

core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodContextUpdateWorker.java, core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodEndWorker.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java
=> Fixed updating Skipped status

core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/RetryAnalyzer.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/common/DataProviderTest.java
Added another test for crashing data providers.
Fixes #159
=> Improved crashed data provider handling

.gitignore, core/src/main/java/eu/tsystems/mms/tic/testframework/internal/AssertionChecker.java, core/src/main/java/eu/tsystems/mms/tic/testframework/internal/CollectedAssertions.java, core/src/main/java/eu/tsystems/mms/tic/testframework/logging/ContextIdsPatternConverter.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/model/steps/TestStep.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/utils/ExecutionContextController.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/utils/ExecutionContextUtils.java, core/src/main/java/eu/tsystems/mms/tic/testframework/utils/Timer.java, docs/src/docs/pageobject/pageobjects-overview.adoc, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/Page.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/UITestUtils.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverProxyUtils.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverSessionsManager.java, image-processing/src/main/java/eu/tsystems/mms/tic/testframework/layout/LayoutCheck.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/execution/ExpectedFailsTests.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/execution/RetryTests.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/execution/TestStatusTest.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/reporting/ScreenshotsTest.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/UITestUtilsTest.java, report-model/src/main/java/eu/tsystems/mms/tic/testframework/report/TestStepLogAppender.java
Added getters to prevent NPEs.
Fixes #173
=> Added Optional getters for thread locals #173

docs/build.gradle, docs/src/docs/docinfo-footer.html
The footer of Testerra docs get links to imprint and privacy policy of testerra.io.
=> Added imprint and privacy policy to footer of Testerra docs

core-interop/build.gradle, core/src/main/resources/log4j2.xml, docs/src/res/log4j2.xml, integration-tests/src/test/resources/log4j2-test.xml
Prevents log4shell vulnerability (https://logging.apache.org/log4j/2.x/security.html)
=> Upgraded log4j and disabled message lookups in config xml.

core-interop/build.gradle
Update log4j lib to 2.16.0 to completly remove message lookups: https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
=> Updated log4j to 2.16.0

docs/src/docs/gettingstarted/manual-steps.adoc, docs/src/docs/modules/connectors.adoc, docs/src/docs/modules/mail-connector.adoc, docs/src/docs/utilities/proxy-utilities.adoc
Improved the documenation about ProxyUtils with some additional hints.
=> Improved ProxyUtils documentation

core-interop/src/main/java/eu/tsystems/mms/tic/testframework/constants/TesterraProperties.java, docs/src/docs/properties/property-attributes.adoc, docs/src/docs/properties/webdriver-props.adoc, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverCapabilities.java, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/AbstractWebDriverConfiguration.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverManagerConfig.java
Added support for `platform` and `platformName` capabilites via. `tt.browser.platform`
Fixes #191 
=> Added support for platform and platformName. Fixes #191

core-interop/src/main/java/eu/tsystems/mms/tic/testframework/constants/TesterraProperties.java, docs/src/docs/gettingstarted/manual-steps.adoc, docs/src/docs/properties/webdriver-props.adoc, docs/src/docs/webdrivermanager/webdrivermanager-sessions.adoc, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverCapabilities.java, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java, driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverRequest.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverManagerConfig.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/desktop/WebDriverMode.java, integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/DriverAndGuiElementTest.java
Remove support of `WebDriverMode`.
Fixes #190
=> Removed WebDriverMode

docs/src/docs/gettingstarted/logging.adoc
Added user documentation for `Loggable` interface.
=> Added documentation for logging

driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverCapabilities.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/AbstractWebDriverConfiguration.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverManagerConfig.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverSessionsManager.java
Platform attribute was not set to new created `DesktopWebDriverRequest`.
=> Fixed setting platform attribute to DesktopWebDriverRequest

report-ng/app/src/components/failure-aspects/failure-aspects.html
Fixed failure aspects switch for filtering.
=> Fixed failure aspects switch

driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/factory/PageFactory.java
=> Added NPE check to PageFactory loop detection

driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/DefaultPageFactory.java
Description
Fixes NPS at page loop detection (taken from Testerra 1)
- [ x] I have performed a self-review of my own code
=> Fixed NPE in loop detection of DefaultPageFactory

core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/start/MethodParametersWorker.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/utils/ExecutionContextUtils.java
Removed an useless check for injected methods at setup methods. It's a relict from a former framework version not not needed anymore.
=> Removed check for injected methods at setup methods.

.gitignore, docs/src/docs/gettingstarted/manual-steps.adoc, docs/src/docs/modules/property-manager.adoc
* Updated the Gradle usage in the manual.
* Updates description of loading property files at Testerra start
=> Updated Testerra manual

docs/src/docs/browsercaps/common-browser-caps.adoc
=> Fixed setting caps for a DesktopWebDriverRequest

core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodContextUpdateWorker.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java, integration-tests/src/test/java/io/testerra/test/pretest_status/DataProviderTest.java, integration-tests/src/test/java/io/testerra/test/status/CheckTestStatusTest.java
A data provider test with collected assertions was in status `SKIPPED` instead of `FAILED`.
=> Fix test status at data provider tests

report-ng/app/package-lock.json, report-ng/app/package.json
? loader-utils to version 2.0.4
? minimatch to version 3.1.2
Please include a summary of your changes and which issue(s) you fixed. Please include relevant motivation and context as well. 
=> npm audit fix

report-ng/app/src/components/method-details/details.ts
Copying the stacktrace of an error in the Error Details view now also contains the message of the error.
=> added message of exception to stacktrace copy

driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/AbstractWebDriverCore.java
Fixed equals check in AbstractWebDriverCore to prevent NPEs.
=> Make equals check safe for NPE

.gitignore, README.md, docs/build.gradle, docs/src/docs/what-is-testerra.adoc
Updated company name to Telekom MMS in official documentation. 
The license blocks in every file will not updated because they belongs to the creation date of every file. 
=> Updated company name to Telekom MMS

core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/RetryAnalyzer.java
This changes fixes an issue with handling properties in RetryAnalyzer. In some cases an NPE could be thrown.
=> Fixed to prevent NPE at retry analyzer (part2)

docs/src/docs/pageobject/components.adoc
Updated manual with an example to get access to website elements which located outside of a container.
Fixes #265 
=> Updated components doc

integration-tests/src/test/java/io/testerra/test/pretest_status/FailedSetupMethodTests.java, integration-tests/src/test/java/io/testerra/test/status/CheckTestStatusTest.java
Just some status tests which were missing until now. :-)
=> Added some status tests with failed before and after methods

core/build.gradle, core/src/main/java/eu/tsystems/mms/tic/testframework/utils/PdfUtils.java
The pdf version was too old to handle current pdfs, so I upgraded it and adapted the api
=> Upgrade pdf box

build.gradle, core/build.gradle, integration-tests/src/test/java/io/testerra/test/pretest_status/DataProviderTest.java, integration-tests/src/test/java/io/testerra/test/pretest_status/RetryTests.java, integration-tests/src/test/java/io/testerra/test/status/CheckTestStatusTest.java, integration-tests/src/test/resources/test.properties
Updated TestNG to the latest version.
(also updated status tests)
=> Upgrade TestNG to 7.8.0

core/src/main/java/eu/tsystems/mms/tic/testframework/common/Testerra.java, docs/src/docs/properties/execution-probs.adoc, docs/src/docs/properties/property-attributes.adoc
Removed a very outdated and unused property.
=> Removed unused property

core/build.gradle, integration-tests/src/test/resources/test.properties
Removed dependencies which were never used in `FileUtils`.
=> Removed unused FileUtils dependencies

report-ng/app/src/components/failure-aspects/failure-aspects.html, report-ng/app/src/components/failure-aspects/failure-aspects.ts
add a method in failure-aspect to parse html elements to cheracter entities inside message in Failure Aspect page
=> parse html elements inside message of display failure aspect

driver-ui/build.gradle
Reverted removed OpenCV deps needed by some image based actions in `DesktopWebDriverUtils`
=> Reverted OpenCV deps to driver-ui module

core/src/main/java/eu/tsystems/mms/tic/testframework/common/PropertyManager.java, core/src/main/java/eu/tsystems/mms/tic/testframework/report/Report.java, core/src/main/java/eu/tsystems/mms/tic/testframework/utils/FileUtils.java, driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/layout/LayoutCheck.java, integration-tests/src/test/resources/Smoke.xml
Fix creating of layout check reference images in multi module Gradle projects.
=> Update directory handling in multi-module Gradle projects

report-ng/app/src/components/logs/logs.ts
Bring back the feature of log messages in log view that provide links to method contexts.
=> Add method context to log messages

report-ng/app/src/components/logs/logs.ts
=> Fix log filter
