- docs/src/docs/gettingstarted/system-proxy.adoc
- docs/src/docs/utilities/file-downloader.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/FileDownloader.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverProxyUtils.java
This PR fixes NPE in FileDownloader when no target file is given.
It also improves the proxy setup for testing environments and updates the proxy setup documentation.
> Fixed NPE in FileDownloader when no target file is given

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/model/context/SessionContext.java
- driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverFactory.java
- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
This PR moves the code for initializing a `SessionContext` to the abstract `WebDriverFactory`. That improves error robustness when reading `SessionContext.getRemoteSessionId()`
> Initialize SessionContext in abstract WebDriverFactory

- driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/DesktopGuiElementCore.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/GuiElementAdditionalTests.java
---
name: Pull Request for fixing issue #11 
about: Create a pull request for your changes
title: 'Bugfix issue #11 '
labels: enhancement
assignees: ''
---
Added a condition that does not prepend "./" to Xpath when trying to get subelement and selecting them by xpath which starts with opening parenthese, so the xpath remain unchanged and works properly. Added dedicated test for that in GuiElementAdditionalTests.
Fixes #11
> [WIP] adjust xpath correction

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/AbstractWebDriverCore.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/GuiElementAdditionalTests.java
fixes for corrections of Xpath with parentheses in correctToRelativeXPath() and addition test for it
---
name: Fix for issue #11
about: Create a pull request for your changes
title: ''
labels: enhancement bugfix
assignees: ''
---
Fixed xpath correction for xpathes with parenthesis and adding a test for that.
Fixes #11 
> Fixing correction of xpath with parentheses in correctToRelativeXPath() in testerra2

- report-ng/src/main/java/eu/tsystems/mms/tic/testframework/listeners/CopyReportAppListener.java
Previously the URI to the JAR file of report-ng was constructed using the unescaped path. This would fail if there are carecters in the path that are not valid in the path component of a URI (e.g. spaces). This pull request changes the construction of the URI to use the escaped path component and makes report-ng work with local maven repos that have spaces and other
special characters in their path.
Fixes #33 
Tested on Windows in Git Bash and on Ubuntu 20.04.
> Use escaped path in report-ng when accessing JAR

- report-ng/app/src/services/statistic-models.ts
- report-ng/app/src/services/statistics-generator.ts
* Fixed back references class context for method context when retrieving method details.
* That fixes referencing the wrong class, when a method has been run multiple times in different test contexts.
> Fixed retrieving raw class context for MethodDetails.

- README.md
Fix label for e-mail badge (now correctly refers to the Testerra team)
> Fix: label for email badge in readme

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverSessionsManager.java
Added exception message for missing browser configuration.
```
No WebDriverFactory registered for browser 'adsasasd'
```
```
No browser configured. Please define one in WebDriverRequest.setBrowser() or property 'tt.browser'
```
Fixes #79
> Improved logging for missing browser configuration. Fixes #79.

- driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/core/DesktopGuiElementCore.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/WebDriverUtils.java
This is a backport from Testerra 2 element screenshot. It fixes cropping the image, when the element dimensions are bigger than the screenshot dimensions.
- Fixes #86 
> Fixed cutting element image from full screenshot.

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/WebDriverUtils.java
The position and size of the viewport could return floating numbers which failed by `NumberFormatException`.
Fixes #89
> Parse viewport pixel from double, fixes #89

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/DefaultReport.java
This PR fixes a bug in the `Report.getRelativePath()`, which was not able to create a relative path from a file AFTER the report has been finalized via. `Report.finalizeReport()`
- Fixes a bug in the platform connector, which syncs files AFTER report finalization.
> Fixed creating relative report path.

- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
Prevents creating empty `TestStepActionEntry` items in test steps.
> Fix for empty test step action entries when there is actually no screenshot id present

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/model/context/SessionContext.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverRequest.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/AbstractWebDriverRequest.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/webdrivermanager/WebDriverManagerTest.java
The SessionContext clones the complete WebDriverRequest object after instantiation. In case of existing capabilities the following exception occues because the Capabililies object is not clonable.
`org.apache.commons.lang3.SerializationException: IOException while reading or closing cloned object data`
I've added a special handling of cloning capabilites in `AbstractWebDriverRequest`
> Capabilites of DesktopWebDriverRequest not clonable

- driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java
Dont throw `Exception` when the base URL could not be opened for some reason.
> Fixed crashed test when baseUrl could not be opened.

- docs/src/docs/best-practices/prefer-assertions.adoc
- docs/src/docs/guielement/guielement-checks.adoc
Short update for usage of `isDisplayed`. Added a warning of using it for verifications.
> Updated docs for usage of isDisplayed()

- core-interop/src/main/java/eu/tsystems/mms/tic/testframework/utils/ProxyUtils.java
- docs/src/docs/browsercaps/proxy-setup.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverProxyUtils.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/ProxyUtilsTest.java
Since Firefox 90 the FTP proxy settings are no longer supported: https://blog.mozilla.org/addons/2021/04/15/built-in-ftp-implementation-to-be-removed-in-firefox-90/.
There is also a note from Selenoid developers: https://github.com/aerokube/selenoid-container-tests/issues/11
Therefor `WebDriverProxyUtils` shouldn't set it per default, but only proxy for HTTP or HTTPS.
> Removed FTP proxy settings from default proxy

- core/src/main/java/eu/tsystems/mms/tic/testframework/annotations/InDevelopment.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/annotations/InfoMethod.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/annotations/New.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/annotations/ReadyForApproval.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/annotations/SupportMethod.java
- docs/src/docs/execution/execution-annotation.adoc
Marks some annotations as `@deprecated`
> Marked some orphaned annotations as @deprecated

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/Report.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java
- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
Moves methods from `DefaultReport` implementation to `Report` interface.
> Interfaced AnnotationConverter report methods

- report-ng/app/package-lock.json
- report-ng/app/src/components/method-details/details.ts
Fixes not working "copy to clipboard" feature in report-ng when the application run within frames.
> Fixed copying clipboard when application runs in frames

- docs/src/docs/extending-testerra/events-and-listener.adoc
- docs/src/docs/pageobject/pageobjects-overview.adoc
Based on #176 I updated the part about creating additonal Testerra listener in the official documentation.
> Updated listener part of Testerra docs.

- docs/src/docs/common-attributes.adoc
- docs/src/docs/modules/layout-check.adoc
- docs/src/docs/properties/layout-check-probs.adoc
- docs/src/docs/properties/property-attributes.adoc
Documentation fix about RBG deviation values. Removed documention about deprecated and untested annotated layout check mode.
Fixes #195
> Fixed documentation about RGB deviation #195

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/execution/worker/finish/PageFactoryBufferWorker.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/hooks/DriverUiHook.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/factory/PageFactory.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/pagefactory/PageFactoryTest.java
- integration-tests/src/test/resources/test.properties
The buffer for the PageFactory loop detection buffer was not cleared over the whole test execution. In rare cases like non-parallel dataprovider tests with only one page you have to extend the Testerra property `tt.page.factory.loops`.
With this change the internal buffer is cleared after the method end event. Only within a method there is a default limit of 20 when you create a page of the same type in a row.
Fixes #201 
> Added event for clearing PageFactory loop detection buffer after method end

- core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodContextUpdateWorker.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/ReportingAllStatesTests.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/SetupFailedTests.java
In case of a failed data provider method the method context for the corresponding test method has the state `SKIPPED` and contains the assertion or exception of data provider method.
Note: See #215 for improvement of data provider methods.
Fixes #214 
> Fixed handling if dataprovider method failed

- report-ng/app/package-lock.json
Fixes:
- Improper Verification of Cryptographic Signature in `node-forge`
- json-schema is vulnerable to Prototype Pollution
- Open Redirect in node-forge
- Prototype Pollution in minimist
Recommend releasing bugfix version, as some of these are `Critical`(TM).
FWIW: npm disagreed with Dependabot's assertion that breaking changes be required - this is a plain `npm audit fix`. Updating `webpack-dev-server` as advised did not result in further fixes (and thence is not included).
... Hopefully npm got it right and Dependabot is wrong.
> Dependabot alerts: npm audit fix

- core/src/main/java/eu/tsystems/mms/tic/testframework/common/Testerra.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/constants/TesterraProperties.java
- docs/src/docs/webdrivermanager/webdrivermanager-config.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverRequest.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/webdrivermanager/WebDriverManagerTest.java
Added a new method to DesktopWebDriverRequest to set a custom dimension to the browser window size.
Fixes #228
> Feature/custom browser size to DesktopWebDriverRequest

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultStringAssertion.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/UiElementActionTests.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/UiElementCommonTests.java
Changed the implementation of `hasWords()` assertion:
- Handle every element of the given list of words
- Check non word characters with "\W"
- false:  check with `\b<word>\b`
- true: non-word characters have an impact to `\b` -> fallback to `string.contains(word)`
- count of findings = words.size() -> assertion passed
Fixes #233 
> Fixed hasWords assertion of strings

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverManagerUtils.java
Just removed some outdated methods which are already deprecated in Testerra 1. The class `WebDriverManagerUtils` is not responsible for handling of Browser caps. 
> Removed outdated caps handling

- core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodEndWorker.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java
If configuration methods are fail the `TestStatusUpdateEvent` is never called and the method context is never finalized. (e.g. no correct duration).
> Non-passed configuration methods also needs a finalization.

- report-ng/app/src/components/method-details/method.html
Previously links where automatically parsed and a link was created for them. The resulting html was then escaped in the report so you would see things like <a href="example.com">example.com</a> instead of a link to example.com.
> fix to display innerhtml in Priority messages of the method view

- report-ng/app/src/components/method-details/steps.html
This is done in the steps.html analog to the virtual log view in the logs.html
Fixes #217
> Fixes issue #217 - set logs class in log-view in step logs

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/FailsAnnotationConverter.java
- report-ng/app/src/components/method-details/method.html
Added the validator to the Mapping of the Fails annotation for the report and display it on failed test cases when the validation for the expected failure fails as well. This will also hide the description of the expected failure and the corresponding ticket string if they exist.
Fixes #175
> show message for failed validation in expected fails

- docs/src/docs/guielement/guielement-properties.adoc
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/DriverAndGuiElementTest.java
The usage of the method `getActual()` to get current properties of UiElements was missing. 
> Added usage of `getActual` method for UiElements

- README.md
- build.gradle
- docs/src/docs/gettingstarted/manual-steps.adoc
- docs/src/docs/gettingstarted/system-requirements.adoc
Raised the language level to JDK11.
Fixes #194 
> Updated to JDK11 

- core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/worker/finish/MethodContextUpdateWorker.java
- integration-tests/src/main/java/eu/tsystems/mms/tic/testframework/core/utils/Log4jFileReader.java
- integration-tests/src/test/java/io/testerra/test/pretest_status/DataProviderTest.java
- integration-tests/src/test/java/io/testerra/test/status/CheckTestStatusTest.java
In case of optional assertions a testmethod was set to status `SKIPPED` if the test was part of a dataprovider run.
> Fixed test status of optional in dataprovider test

- docs/src/docs/execution/test-controller.adoc
- docs/src/docs/pageobject/pageobjects-check-annotations.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/Check.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/action/GuiElementCheckFieldAction.java
- integration-tests/src/main/java/eu/tsystems/mms/tic/testframework/core/pageobjects/testdata/PageWithCollectedAndOptionalElement.java
- integration-tests/src/main/java/eu/tsystems/mms/tic/testframework/core/pageobjects/testdata/PageWithCollectedElement.java
- integration-tests/src/main/java/eu/tsystems/mms/tic/testframework/core/pageobjects/testdata/PageWithOptionalElement.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/pagefactory/CheckPageTest.java
Added the `collect` attribute for `@Check`:
````java
@Check(collect = true)
private UiElement uiElement = find(...);
````
Also fixed the `optional` attribute which was not working properly.
Fixes #207 
> Added collected checks for UiElements in pages

- report-ng/app/src/components/classes/classes.html
- report-ng/app/src/components/classes/classes.scss
- report-ng/app/src/components/classes/classes.ts
The table in the Tests view of the report can now be ordered by run id, method name, and class name. When ordering by class name the methods from the same class will be ordered by the method name. Default order is by class name.
> Report: added ordering options to columns in tests view

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultStringAssertion.java
The error message of the hasWords assertion included regular expressions, which were also shown in the testerra report and made it more difficult to read.
Those regular expressions were removed from the error message to improve the readability.
> Removed regular expressions from error message of hasWords assertion

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/UITestUtils.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/DriverAndGuiElementTest.java
Creating screenshots via `UITestUtils` was not safe for non-browser drivers like Appium drivers. Some called methods are not supported by Appium.
I also removed old stuff like taking screenshots with Sikuli `ScreenRegion` because it's only work local but not with remote Selenium servers.
> Fix UITestUtils for non-browser drivers

- core/src/main/java/eu/tsystems/mms/tic/testframework/constants/TesterraProperties.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/RetryAnalyzer.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/report/TestStatusController.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java
Exception in a custom retry analyzer are not catched. Therefor the method context cannot finalized which has impact to the result of a test method.
> Added try/catch when custom retry analyzers are executed

- core/src/main/java/eu/tsystems/mms/tic/testframework/common/Testerra.java
- docs/src/docs/execution/execution-highlighting.adoc
- docs/src/docs/properties/execution-probs.adoc
- docs/src/docs/properties/property-attributes.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/JSUtils.java
- driver-ui/src/main/resources/snippets/highlight.js
The new property `tt.demomode.timeout` allows to set a custom timeout where the highlighting is removed. A value of `0` means an _infinite_ timeout.
> Added property to change timeout of uielement highlighting

- docs/src/docs/gettingstarted/logging.adoc
- docs/src/res/log4j2.xml
The used HTTP client in Selenium 4 spams the logs with huge number of request and response information when using `DEBUG` level. This PR updates the example for a custom `log4j2.xml`.
> Updated log4j2.xml example with Selenium 4 specifics

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/AbstractUiElementList.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/UiElementListTests.java
When calling `hasNext()` on an `UiElementList`, the result was always `false`, because the size of the list was not initialized.
I wrote a test which failed before my fix.
I added the initialization of `iteratorSize` to the constructor of `AbstractUiElementList`. This fixed the problem and made the test pass.
In a second commit, for consistency I also added the initializaion of `size` to the constructor.
> UiElementList Iterator

- report-ng/app/src/components/method-details/details.html
- report-ng/app/src/components/method-details/details.scss
- report-ng/app/src/components/method-details/details.ts
The issue was that there was overflowing in the error details view. There were two main reasons: if the title of the error reason was too long and without spaces, the title was not wrapping to the next line. Same issue with the logs of stack traces. 
I fixed both using `overflow-wrap: anywhere;`
Before: 
After:
> fixed overflowing of stacktrace lines and assertion error title

- report-ng/app/src/components/failure-aspects/failure-aspects.html
- report-ng/app/src/components/method-details/details.scss
- report-ng/app/src/components/method-details/method.html
- report-ng/app/src/components/method-details/method.scss
- report-ng/app/src/components/method-details/method.ts
- report-ng/app/src/services/statistic-models.ts
* fixed spelling mistake Statuses -> Status
* on dashboard is a top 3 failure aspects list: if there is a failure aspect that has one failed test and one expected failed test, the color of the icon represents the expected failed color (dark red), but it should display the failed color (light red)
* added a check: if the color is dark red (expected failed), it additionally checks if there is a test with the failed-status. If that is true, it returns light red (failed), if not it returns the color that was originally calculated
> Bugfix failure aspects

- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
Fixed `ContextExporter` to prevent NPEs in metrics export.
> Prevent for NPEs in ContextExporter

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverManagerUtils.java
Closing the chrome session could left Chrome tasks on Windows, which takes much CPU resources. This only occures with desktop mode of Chrome, not with headless mode.
It's not clear, why this happens since Selenium 4. 
This PR provides a 'safer' close of the current session. Before `webdriver.quit()` all windows or tabs are closed with `webdriver.close()`.
> Added a closing current window before closing the whole session

- report-ng/app/src/components/classes/classes.html
Added a minor note in test table that filter criteria could only match to configuration methods: Coming from Failure aspects the selected aspect only occurs in a configuratio method.
The little hint is removed if switch for config methods is active:
> Added note if filter criteria could only match to configuration methods.

- build.gradle
- docs/src/docs/selenium4/selenium4-webdriver-bidi.adoc
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/SeleniumBiDiApiTests.java
Update Selenium to the latest version `4.16.1`: https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG
I also updated the W3C bidi example for listing to browser console logs.
> Update Selenium to 4.16.1

- core/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/AbstractPropertyAssertion.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/FileAssertion.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/ObjectAssertion.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/QuantityAssertion.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/StringAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/AbstractTestedPropertyAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultBinaryAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultFileAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultObjectAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultPatternAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultPropertyAssertionFactory.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultQuantityAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/internal/asserts/DefaultStringAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/DefaultPageAssertions.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/DefaultUiElementAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/PageAssertions.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/UiElementAssertion.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/UiElementBaseAssertion.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/UiElementExpectAttributeTests.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/guielement/UiElementLayoutTests.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/page/PageTests.java
- report-ng-tests/src/main/java/io/testerra/report/test/pages/report/methodReport/ReportDetailsTab.java
- templates/file-header.txt
The StringAssertion interface is no longer inheriting from QuantityAssertion instead both of those interfaces now inherit ObjectAssertion which inherits BinaryAssertion. Also StringAssertion is now restricted to the type String. This is a breaking change since StringAssertion previously was able to use the functions of QuantityAssertion. Since these only worked on numbers this didn't make sense and triggered this change.
These functions moved from QuantityAssertion to ObjectAssertion so StringAssertion can still use them:
-     `boolean is(Object expected)`
-     `boolean is(Object expected, String subject)`
-     `boolean isNot(Object expected)`
-     `boolean isNot(Object expected, String subject)`
Some changes regarding generic types to remove related warnings have been added as well. …
> Refactor stringassertion

- report-ng-tests/src/test/java/io/testerra/report/test/TestDataProvider.java
Fix of failing report test concerning screenshots of collected assertions. Test method test_multipleScreenshotsShown, which checks existence of multiple screenshots, now verifies this for test_takeScreenshotViaCollectedAssertion_fails, too.
Fixes issue #390
- Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] New and existing tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules
> Fix of failed Screenshot Test in report-ng-test

- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/webdrivermanager/DesktopWebDriverFactoryTest.java
- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
Updated Gson usage in ContextExporter to handle special caps.
Fixes #409 
> Updated Gson builder in ContextExporter

- core/build.gradle
Bump TestNG from 7.8.0 to 7.10.1
> Bump TestNG from 7.8.0 to 7.10.1

- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/webdrivermanager/DesktopWebDriverFactoryTest.java
- report-model/src/main/java/eu/tsystems/mms/tic/testframework/adapters/ContextExporter.java
Reverts telekom/testerra#418
Need a new fix. The current solution eliminate all caps for report.
> Revert "Updated Gson builder in ContextExporter"

- core/src/main/java/eu/tsystems/mms/tic/testframework/common/Testerra.java
Fixes bug #421 by apply a package filter to avoid implementations of `com.google.inject.AbstractModule` that does not fullfill package class will be instantiated.
Concrete class of the fat jar that will force this error is `com.google.inject.util.Modules$OverrideModule`.
Before this fix Testerra tried to invoke the following implementations of `AbstractModule` inside the fat jar:
* Loading module: eu.tsystems.mms.tic.testframework.hook.ReportModelHook
* Loading module: eu.tsystems.mms.tic.testframework.hook.ReportNgHook
* Loading module: com.google.inject.util.Modules$OverrideModule
* Loading module: eu.tsystems.mms.tic.testframework.ioc.CoreHook
* Loading module: com.google.inject.internal.RealMultibinder$PermitDuplicatesModule
* Loading module: …
> Fixes bug #421 - Run Testerra as part of fat jar standalone application

- report-ng/app/src/components/threads/threads.html
- report-ng/app/src/components/threads/threads.ts
- report-ng/app/src/styles/mdc.scss
* added class filter for threads view
* filters can not be active at the same time => to prevent this and show user that he cannot use them at the same time, filters will be disabled
* note: to achieve this, we need extra variables `_selectedClass` and `_selectedStatus`; otherwise after refreshing the page while we have an active filter, the other both filter fields will not be disabled anymore
* note: when we have one of the select filters active (class or status) the selection was removed out of the select box although the filter remained active. This caused that you were neither able to deactivate the filter nor activate another filter since they were disabled 
=> to solve this i added "ref" to the mdc-selects which modify `statusSelect` and `classSelect` 
=> these will put the …
> added class filter for threads view

- build.gradle
- core/src/main/java/eu/tsystems/mms/tic/testframework/utils/ProxyUtils.java
- docs/src/docs/selenium4/selenium4-cdp.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/testing/SeleniumChromeDevTools.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverProxyUtils.java
- The usage of a local WebDriver and a proxy with no set properties caused an Error: `a value is required for '--proxy <PROXY>' but none was supplied` so that the browser session could not be started.
- The corresponding Selenium-Issue (https://github.com/SeleniumHQ/selenium/issues/14162) was fixed for version `4.23.0`
> Fix/local WebDriver proxy

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/JSUtils.java
Changed again the behaviour of `element.scrollIntoView`. Now the JS `window.sroll()` method is used instead of `arguments[0].scrollIntoView`.
The scrolling is much more stable and it is also allowed to scroll up.
> Changed UiElement.scrollIntoView to 'window.scroll()' solution

- docs/src/docs/selenium4/selenium4-cdp.adoc
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/ResponsiveClassFinder.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/testing/SeleniumChromeDevTools.java
- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/ChromeDevTools.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/playground/ChromeDevToolsTests.java
For testing responsive design the Chrome device emulation mode could be very helpful to simulate mobile devices.
This PR adds a method to easy use the emulation mode.
> Added helper method to use CDP device emulation

- driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/AbstractPage.java
remove deprecated method (assertPageIsShown/-NotShown) from AbstractPage
> remove deprecated methode from AbstractPage

- report-ng/app/package-lock.json
- report-ng/app/package.json
- report-ng/app/src/components/log-view/log-line.html
- report-ng/app/src/services/status-converter.ts
- report-ng/app/src/value-converters/html-escape-value-converter.ts
- report-ng/app/src/value-converters/html-value-converter.ts
- report-ng/app/tsconfig.json
* html escape was accidently removed in this PR: https://github.com/telekom/testerra/pull/433/files#diff-82f6273a45570c3c56e82b8284b21f36b6f3d7486ffe4ee9d120c6ec9d314c95
* i reverted the change
* added ? and " as searchable strings 
* note: there is a known bug: if you search "&", escaped characters are converted and marked, see examples: 
> added html escape to log messages

- core/src/main/java/eu/tsystems/mms/tic/testframework/report/DefaultReport.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/report/Report.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/utils/FileUtils.java
- core/src/main/java/eu/tsystems/mms/tic/testframework/utils/PdfUtils.java
- integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/pagefactory/PageFactoryTest.java
- report-model/src/main/java/eu/tsystems/mms/tic/testframework/listeners/GenerateJUnitXML2ReportListener.java
- report-ng/src/main/java/eu/tsystems/mms/tic/testframework/hook/ReportNgHook.java
- report-ng/src/main/java/eu/tsystems/mms/tic/testframework/listeners/CopyReportAppListener.java
Since using the updated libs of `commons-io:commons-io` (#426) there is an issue in generating the final report directory in a special case:
Running a test of a Gradle module with `gradle submodule:test` the `user.dir` is the project root but `java.io.File` creates files under `<root>/submodule`. Current `FileUtils` class is using `java.nio.Path` which tries to operate only the real `user.dir`. 
Under Windows the report can be generated, but an old version cannot be deleted. Under Linux there is an exception at moving the report from temp to the final directory.
This PR migrates all file operations in `DefaultReport` to `java.nio.Path`. In case of running Gradle tests in submodules, the report will be placed in the real `user.dir`:
- `gradle submodule:test` --> `<project …
> Migrate DefaultReport from File to Path
